### ISSUE TITLE
[Suggestion] Toxic waste barrel

### ISSUE THREAD

**Issue by Ekkelus** [Ekkelus/ECO-Realism#7]
Only tailings can be stored in this object.

**Comment by Yamor123** [comment]
I couldn't figure out yet how those InventoryRestrictions work.

But theres a possible workaround. We could use Fuel slots instead of ordinary Storage slots.
The drawbacks of this method are the following: 
1. Tailings need a fuel value (only a visual thing)
2. 1 Tailing per Container will be locked in the "current fuel" slot ( i might have a solution to that)
3. because of 2 its possible to destroy tailings by placing and removing that container, as you dont get that one tailing back
4. Container is "Out of fuel" so opening it will always open "Status" tab first

I'll do some more testing and report what i got
